export const partsItems = [
    {
        title: 'Ролик системы когель',
        image: '/images/parts/ролик-система-когель.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ролик системы KOGEL 629-K',
        image: '/images/parts/РОЛИК-СИСТЕМЫ-KOGEL-629-K.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ролик системы SCHMITZ 608-ST',
        image: '/images/parts/РОЛИК-СИСТЕМЫ-SCHMITZ-608-ST.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ролик системы SESAM 609-S',
        image: '/images/parts/РОЛИК-СИСТЕМЫ-SESAM-609-S.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ролик системы TSE 609-ELP',
        image: '/images/parts/РОЛИК-СИСТЕМЫ-TSE-609-ELP.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ролик системы TSE 609-T',
        image: '/images/parts/РОЛИК-СИСТЕМЫ-TSE-609-T.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ролик-EDSHA-1',
        image: '/images/parts/Ролик-EDSHA-1.png',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ролик оцинкованный',
        image: '/images/parts/Ролик-оцинкованный.png',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Штанга натяжения тента',
        image: '/images/parts/ШТАНГА-НАТЯЖЕНИЯ-ТЕНТА.gif',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Крючок оцинкованный',
        image: '/images/parts/КРЮЧОК-ОЦИНКОВАННЫЙ.png',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Крючок пластмассовый',
        image: '/images/parts/КРЮЧОК-ПЛАСТМАССОВЫЙ.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Наконечник на трос TIR',
        image: '/images/parts/НАКОНЕЧНИК-НА-ТРОС-TIR.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'подкладка пластиковая A-51',
        image: '/images/parts/подкладка-пластиковая-а-51.png',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'подкладка пластиковая A-20',
        image: '/images/parts/ПОДКЛАДКА-ПЛАСТИКОВАЯ-А-20.png',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'подкладка пластиковая A-34',
        image: '/images/parts/ПОДКЛАДКА-ПЛАСТИКОВАЯ-А-34.png',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'подкладка пластиковая',
        image: '/images/parts/Подкладка-пластиковая.png',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скоба бортавая колебательная вертикальная',
        image: '/images/parts/СКОБА-БОРТОВАЯ-КОЛЕБАТЕЛЬНАЯ-ВЕРТИКАЛЬНАЯ.webp',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скоба бортавая на квадратном основании',
        image: '/images/parts/СКОБА-БОРТОВАЯ-НА-КВАДРАТНОМ-ОСНОВАНИИ.webp',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скоба загнутая французская',
        image: '/images/parts/СКОБА-ЗАГНУТАЯ-ФРАНЦУЗСКАЯ.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Трос TIR с наконечником',
        image: '/images/parts/ТРОС-TIR-с-наконечником.png',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Эспандер черный (полипропиленовый)',
        image: '/images/parts/ЭСПАНДЕР-ЧЁРНЫЙ-(ПОЛИПРОПИЛЕНОВЫЙ).jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скоба поворотная',
        image: '/images/parts/Скоба-поворотная.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скобы тентовые, бортовые закругленные',
        image: '/images/parts/Скобы-тентовые,-бортовые-закругленные.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скобы тентовые, бортовые прямоугольные',
        image: '/images/parts/Скобы-тентовые,-бортовые-прямоугольные.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Средняя стойка SCHMITZ',
        image: '/images/parts/Средняя-стойка-SCHMITZ.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Стопорный трос сдвижного механизма крыши(комплект)',
        image: '/images/parts/Стопорный-трос-сдвижного-механизма-крыши(комплект).jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Табличка ADR',
        image: '/images/parts/Табличка-ADR.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Табличка TIR',
        image: '/images/parts/Табличка-TiR.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Табличка А (складная)',
        image: '/images/parts/Табличка-А-(складная).jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Фиксатор двери',
        image: '/images/parts/Фиксатор-двери.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Фиксатор замка двери Т-образный',
        image: '/images/parts/Фиксатор-замка-двери-Т-образный.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Фиксатор тента сдвижной крыши',
        image: '/images/parts/Фиксатор-тен-та-сдвижной-крыши.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Фиксатор Т-образный для дверей фургона',
        image: '/images/parts/Фиксатор-Т-образный-для-дверей-фургона.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Фирменный календарь 2024 года ИнтерТентСервис',
        image: '/images/parts/Фирменный-календарь-2024-года-ИнтерТентСервис.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Шарнир сдвижной крыши',
        image: '/images/parts/Шарнир-сдвижной-крыши.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'S-крюк (оцинкованный)',
        image: '/images/parts/S-крюк-(оцинкованный).jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Амортизатор газовый каретки сдвижной крыши тип-1',
        image: '/images/parts/Амортизатор-газовый-каретки-сдвижной-крыши-тип-1.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Амортизатор газовый каретки сдвижной крыши тип-2',
        image: '/images/parts/Амортизатор-газовый-каретки-сдвижной-крыши-тип-2.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Бортовой замок',
        image: '/images/parts/Бортовой-замок.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Втулка петли ворот KOGEL',
        image: '/images/parts/Втулка-петли-ворот-KOGEL.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Держатель задней балки сдвижной крыши',
        image: '/images/parts/Держатель-задней-балки-сдвижной-крыши.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Замок ворот внутренний (правый левый)',
        image: '/images/parts/Замок-ворот-внутренний-(правый-левый).jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Замок ремня натяжения оцинкованный',
        image: '/images/parts/Замок-ремня-натяжения-оцинкованный.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Замок стойки алюминиевого борта 400-600-800 мм',
        image: '/images/parts/Замок-стойки-алюминиевого-борта-400-600-800-мм.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Защёлка бортового замка',
        image: '/images/parts/Защёлка-бортового-замка.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Информационная табличка для длинномера алюминиевая',
        image: '/images/parts/Информационная-табличка-для-длинномера-алюминиевая.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Крепление амортизатора каретки',
        image: '/images/parts/Крепление-амортизатора-каретки.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Крепление тента крыши',
        image: '/images/parts/Крепление-тента-крыши.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Кронштейн средней стойки',
        image: '/images/parts/Кронштейн-средней-стойки.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Крыша сдвижная 13,6м для полуприцепа',
        image: '/images/parts/Крыша-сдвижная-13,6м-для-полуприцепа.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Люверсы 12мм оцинкованные',
        image: '/images/parts/Люверсы-12-мм-оцинкованные.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Люверсы 16мм оцинкованные',
        image: '/images/parts/Люверсы-16-мм-оцинкованные.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Люверсы 20мм оцинкованные',
        image: '/images/parts/Люверсы-20-мм-оцинкованные.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Люверсы для тентов 40мм оцинкованные',
        image: '/images/parts/Люверсы-для-тентов-40-мм-оцинкованные.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Люверсы овальные 42х22мм',
        image: '/images/parts/Люверсы-овальные-42х22-мм.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Люверсы прямоугольные для тентов 27х8мм',
        image: '/images/parts/Люверсы-прямоугольные-для-тентов-27х8-мм.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Люверсы прямоугольные для тентов 38х8мм',
        image: '/images/parts/Люверсы-прямоугольные-для-тентов-38х8-мм.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Материал тентовый 630-900гр на м.кв',
        image: '/images/parts/Материал-тентовый-630-900-гр-на-м.кв.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Механизм натяжения бокового тента тип-1',
        image: '/images/parts/Механизм-натяжения-бокового-тента-тип-1.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Механизм натяжения бокового тента тип-2',
        image: '/images/parts/Механизм-натяжения-бокового-тента-тип-2.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Наконечник на трос с крючком d-6,5-8,5',
        image: '/images/parts/Наконечник-на-трос-с-крючком-d-6,5-8,5.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Наконечник нижний для профиля 27мм тип-1',
        image: '/images/parts/Наконечник-нижний-для-профиля-27-мм-тип-1.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Наконечник нижний для профиля 27мм тип-2',
        image: '/images/parts/Наконечник-нижний-для-профиля-27-мм-тип-2.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ответная часть бортового замка',
        image: '/images/parts/Ответная-часть-бортового-замка.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Палец петли борта',
        image: '/images/parts/Палец-петли-борта.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Палец петли борта тип-2',
        image: '/images/parts/Палец-петли-борта-тип-2.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Петля борта (комплект)',
        image: '/images/parts/Петля-борта-(комплект).jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Петля ворот KOGEL',
        image: '/images/parts/Петля-ворот-KOGEL.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Петля для ворот',
        image: '/images/parts/Петля-для-ворот.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Петля крепления груза тип-1',
        image: '/images/parts/Петля-крепления-груза-тип-1.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Петля крепления груза тип-2',
        image: '/images/parts/Петля-крепления-груза-тип-2.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Пластиковый шарнир сдвижной крыши',
        image: '/images/parts/Пластиковый-шарнир-сдвижной-крыши.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Пластиковый шарнир сдвижной крыши 570мм',
        image: '/images/parts/Пластиковый-шарнир-сдвижной-крыши-570мм.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Пластиковый шарнир сдвижной крыши 650мм-570мм-400мм',
        image: '/images/parts/Пластиковый-шарнир-сдвижной-крыши-650мм-570мм-400мм.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Подкладка скобы пластиковая',
        image: '/images/parts/Подкладка-скобы-пластиковая.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Подножка для борта',
        image: '/images/parts/Подножка-для-борта.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ремень с плоским крюком для замка оцинкованный',
        image: '/images/parts/Ремень-с-плоским-крюком-для-замка-оцинкованный.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ремкомплект пистона крепления тента крыши TIR',
        image: '/images/parts/Ремкомплект-пистона-крепления-тента-крыши-TIR.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ремни пвх с пряжкой',
        image: '/images/parts/ремни-пвх-с-пряжкой.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ремонтная петля ворот KOGEL',
        image: '/images/parts/Ремонтная-петля-ворот-KOGEL.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ролик боковой стойки',
        image: '/images/parts/Ролик-боковой-стойки.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ролик боковой стойки EDSHA',
        image: '/images/parts/Ролик-боковой-стойки-EDSHA.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Ролик боковой стойки Schmitz',
        image: '/images/parts/Ролик-боковой-стойки-Schmitz.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Роликовая каретка сдвижной крыши',
        image: '/images/parts/Роликовая-каретка-сдвижной-крыши.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Роликовая тележка для сдвижной крыши',
        image: '/images/parts/Роликовая-тележка-для-сдвижной-крыши.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Роликовая тележка сдвижной крыши',
        image: '/images/parts/Роликовая-тележка-сдвижной-крыши.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скоба бортовая (французская)',
        image: '/images/parts/Скоба-бортовая-(французская).jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скоба бортовая круглая тип-1',
        image: '/images/parts/Скоба-бортовая-круглая-тип-1.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скоба бортовая круглая тип-2',
        image: '/images/parts/Скоба-бортовая-круглая-тип-2.jpg',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скоба колебательная',
        image: '/images/parts/Скоба-колебательная.webp',
        price: 0,
        currency: 'BYN',
    },
    {
        title: 'Скоба колебательная вертикальная Н-37мм',
        image: '/images/parts/Скоба-колебательная-вертикальная-Н-37-мм.jpg',
        price: 0,
        currency: 'BYN',
    },
];
